#  _              _    _
# | |            | |  (_)
# | | ___ __ ___ | | ___ _ __  _ __   ___ _   _
# | |/ / '_ ` _ \| |/ / | '_ \| '_ \ / _ \ | | |
# |   <| | | | | |   <| | | | | | | |  __/ |_| |
# |_|\_\_| |_| |_|_|\_\_|_| |_|_| |_|\___|\__, |
#                                          __/ |
#                                         |___/
# alacritty config

# {{{ THEMES
schemes:
  everforest_dark: &everforest_dark
    primary:
      background: "#1e2327"
      foreground: "#d3c6aa"

    normal:
      black: "#4b565c"
      red: "#e67e80"
      green: "#a7c080"
      yellow: "#dbbc7f"
      blue: "#7fbbb3"
      magenta: "#d699b6"
      cyan: "#83c092"
      white: "#d3c6aa"

    bright:
      black: "#4b565c"
      red: "#e67e80"
      green: "#a7c080"
      yellow: "#dbbc7f"
      blue: "#7fbbb3"
      magenta: "#d699b6"
      cyan: "#83c092"
      white: "#d3c6aa"

  seafoam_pastel: &seafoam_pastel
    primary:
      background: "#243435"
      foreground: "#d4e7d4"

    normal:
      black: "#757575"
      red: "#825d4d"
      green: "#728c62"
      yellow: "#ada16d"
      blue: "#4d7b82"
      magenta: "#8a7267"
      cyan: "#729494"
      white: "#e0e0e0"

    bright:
      black: "#8a8a8a"
      red: "#cf937a"
      green: "#98d9aa"
      yellow: "#fae79d"
      blue: "#7ac3cf"
      magenta: "#d6b2a1"
      cyan: "#ade0e0"
      white: "#e0e0e0"

  sonokai_espresso: &sonokai_espresso
    primary:
      background: "#312c2b"
      foreground: "#e4e3e1"

    normal:
      black: "#1f1e1c"
      red: "#f86882"
      green: "#a6cd77"
      yellow: "#f0c66f"
      blue: "#81d0c9"
      magenta: "#9fa0e1"
      cyan: "#f08d71"
      white: "#e4e3e1"

    bright:
      black: "#1f1e1c"
      red: "#f86882"
      green: "#a6cd77"
      yellow: "#f0c66f"
      blue: "#81d0c9"
      magenta: "#9fa0e1"
      cyan: "#f08d71"
      white: "#e4e3e1"
# }}}

#####################
# Select Theme Here #
#####################
colors: *everforest_dark
draw_bold_text_with_bright_colors: true

###########
# Fonts   #
###########
font:
  normal:
    family: CaskaydiaCove Nerd Font Mono

###################
# Window Settings #
###################
env:
  TERM: xterm-256color

window:
  dimensions:
    columns: 180
    lines: 60
  position:
    x: 0
    y: 0
  padding:
    x: 0
    y: 0
  dynamic_padding: false
  # decorations: full
  decorations: none
  title: Alacritty
  dynamic_title: true
  class:
    instance: Alacritty
    general: Alacritty
  gtk_theme_variant: None
  opacity: 0.80

startup_mode: Windowed

cursor:
  style: Beam
  unfocused_hollow: true
  vi_mode_style: Block

selection:
  # This string contains all characters that are used as separators for
  # "semantic words" in Alacritty.
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"

  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: true

scrolling:
  history: 10000
  multiplier: 3

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }
  hide_when_typing: true

live_config_reload: true

shell:
  program: /bin/zsh
# vim: fdm=marker fmr={{{,}}}:
